### ISSUE TITLE
Simultaneous Download Bug

### ISSUE THREAD

**Issue by kanohn** [hama3254/Crunchyroll-Downloader-v3.0#134]
Well, i don't know if its working as expected, but on the options "Simultaneous Download" is marked as 1, and sometimes the program let 2 animes to download at the same time when i put some animes on queue. It don't occour all time, only sometimes..

Prints:
https://ibb.co/Dbxbr1P
https://ibb.co/rbmCMsL

I tried to figure it out and search for "Simultaneous Download" to check the code on source, but it seems it's using dll to make the check?
https://ibb.co/rMF4q96

**Comment by hama3254** [comment]
How did you add the second download?
Was it from the Multi download, from the Queue or added directly?
.
The public variable for the check is also namend `MaxDL` in the Main.vb

**Comment by kanohn** [comment]
I add download to the queue by clicking on "+" button everytime. Also i need to stay with the queue list opened to the download starts automatically, if it's not opened it's not start. So when i need to add more to queue, i close the queue and click on "+" to add. 
Maybe i'm adding on the wrong way?

Prints:
https://ibb.co/dGFGs3c
https://ibb.co/gJ6ctD0

**Comment by hama3254** [comment]
> Also i don't know how to add from "Multi Download", i only see that option on Crunchyroll -> Subtile Download

For crunchyroll just use the overview page of the Anime as url to add, then you get a selection for seasons (if there is more than one) and episodes.
Just select a start episode and a stop episode from the drop down then press download.
It will add each episodes on itself.

**Comment by kanohn** [comment]
I will try that way..

However i made some changes on the code to test and it seems to be fixed for the other way.. you could check to see if its correct and adjust the code..

https://www.diffchecker.com/H8tqPZDi

**Comment by kanohn** [comment]
For do what you said, i need the add on for the browser, right? and enable http server on the options i think.. i have tried that before but got some errors on this add on.. i will post print later..

**Comment by hama3254** [comment]
> For do what you said, i need the add on for the browser, right? and enable http server on the options i think.. i have tried that before but got some errors on this add on.. i will post print later..

you don't have to for crunchyroll you can just use the overview page and add them like a normal episode : https://youtu.be/1g2-QQajZ5Y?t=24


> Edit: When i enable add on support, i got this:
> https://ibb.co/v36fNzr

This happens if there is already something that uses the defaul http port (which is port 80) so if you let any other http server or you have more than one downloader window open it can not bind to that port. 

 
> When i try to add episodes with the add on, i click on "select episodes", but the links don't get javascript: to stop forwarding like this video tutorial: https://www.youtube.com/watch?v=ZHCH3rNWYS8&feature=youtu.be
So, when i try to click on the episode, the page redirect me to the ep page. https://ibb.co/xXPzB1j

the JavaScript that changes the website to allow the selection is part of the downloader and gets importet via the http server which did not work for you so the selection also does not work (like the whole plugin itself)

**Comment by kanohn** [comment]
> you don't have to for crunchyroll you can just use the overview page and add them like a normal episode : https://youtu.be/1g2-QQajZ5Y?t=24
Ah, got it. I tried on this way, but i can only add at least 2 episodes, and the bug of simultaneous download persist, the queue list get 2 episodes at a time to download, even if i mark only 1 in options.

> This happens if there is already something that uses the defaul http port (which is port 80) so if you let any other http server or you have more than one downloader window open it can not bind to that port.

Weird, i have apache server but already changed the port to 8080, so i don't know what can be interfering

**Comment by kanohn** [comment]
https://ibb.co/VmkzbSZ
https://ibb.co/MGXbVdJ

**Comment by hama3254** [comment]
The downloader keeps saved settings, it makes no difference if you set the value to 1 or it loads the value 1 from the registry.
I guess the error is a "false negative" due to the way i updated the running downloads count.
Now i reversed this with instead of checking each download if it's running i amuse they run and reduce the count by the finished ones, with that way it should no longer be possible to get this error.

**Comment by hama3254** [comment]
the release is now here :
https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/v3.7.2

**Comment by kanohn** [comment]
Thanks!

**Comment by hama3254** [comment]
since this should be solved i close this, if there are any new issues just open a new one.

**Comment by kanohn** [comment]
I'm testing the new version now.. the issue persist:
https://ibb.co/svPys6Q
