### ISSUE TITLE
crash on url to big

### ISSUE THREAD

**Issue by ncplus0** [hama3254/Crunchyroll-Downloader-v3.0#193]
Version : 3.7.6
![bug url](https://user-images.githubusercontent.com/72767232/109426280-ac96cb00-79e4-11eb-8eaf-337effc404cc.jpg)

im triing to download the full series **CHERRY MAGIC! THIRTY YEARS OF VIRGINITY CAN MAKE YOU A WIZARD?!**
but the 2 specials episodes it brakes the program, and does not create a log.
i've hadded the print of the bug.
i think its the url is to big, all the others episodes the url is muts smaller
also the multi download of subtitles is not working, only one episode at the time.

also can you create an option to download all the season episodes.

**Comment by ncplus0** [comment]
https://www.crunchyroll.com/pt-br/cherry-magic-thirty-years-of-virginity-can-make-you-a-wizard/cherry-magic-thirty-years-of-virginity-can-make-you-a-wizard-episdio-spin-off-dia-de-so-valentim-episdio-spin-off-rokkaku-801818

and 

https://www.crunchyroll.com/pt-br/cherry-magic-thirty-years-of-virginity-can-make-you-a-wizard/cherry-magic-thirty-years-of-virginity-can-make-you-a-wizard-episdio-spin-off-tsuge-minato-801819

**Comment by hama3254** [comment]
it seems like they are just bad at labelling there stuff `episodeNumber` should be a number that why it fails at `System.Number.StringToNumber`
![grafik](https://user-images.githubusercontent.com/52826614/109427132-39e01c80-79f1-11eb-9ff2-8e863310b17d.png)

**Comment by hama3254** [comment]
i now remove all non digits from that port so it should work now as long CR keeps at least one number in the "number" field.
https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/v3.7.6

**Comment by Alexandre1er** [comment]
I still have the same issue with the special episode of Room Camp (https://www.crunchyroll.com/fr/room-camp/room-camp-sauna-et-casse-crote-et-trois-roues-803840) even though I updated to version 3.7.6.2

**Comment by hama3254** [comment]
> should work now as long CR keeps at least one number in the "number" field.

![grafik](https://user-images.githubusercontent.com/52826614/109714567-d4cc2880-7ba2-11eb-8243-180485d173d7.png)

**Comment by hama3254** [comment]
[the new version has been released.](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/v3.7.7)
it is marked as pre-release because of the mostly untested mkv support.
