### ISSUE TITLE
Download error due to new security changes in Funimation

### ISSUE THREAD

**Issue by NatsuFT36** [hama3254/Crunchyroll-Downloader-v3.0#249]
As will be known in all versions of Crunchyroll Downloader that has the download function in Funimation now it no longer works due to new security modifications and it is not possible to download subs and dubbing either but I don't know if they will have to modify other new codes for downloads.

**Comment by hama3254** [comment]
I need to take a look on that later but what does "security changes" mean?
A quick test suggests that they still don't use a DRM.
![Screenshot_20210414-090545](https://user-images.githubusercontent.com/52826614/114668519-21a63180-9d01-11eb-9c31-ce5ea8eb0abf.png)
The video is loading fine without a DRM on my mobile Firefox
![Screenshot_20210414-090604](https://user-images.githubusercontent.com/52826614/114668597-37b3f200-9d01-11eb-9514-7a3448dcb02d.png)

**Comment by NatsuFT36** [comment]
Supposedly the downloads did not work but from the torrents it was mentioned "site changes in Funimation" so I know it is a new improvement although the audio quality is lost from 256kbps to 128kbps

**Comment by MSI-Toby** [comment]
It appears to break more often on series that were launched this year, like _The World Ends with You The Animation_.

**Comment by hama3254** [comment]
> It appears to break more often on series that were launched this year, like _The World Ends with You The Animation_.

That would be something i can start looking at but i have no premium account so i can't. 

i try the new season from Log Horizon and see if or how many issues happen for the 12 Episodes, the first one looks flawless for now. 
![grafik](https://user-images.githubusercontent.com/52826614/114728573-7f596e80-9d3f-11eb-84b5-531b42220c8f.png)

**Comment by NatsuFT36** [comment]
I was downloading the Shingeki no Kyojin series with a premium account but it was throwing an error with an audio and video format and the subs were not downloading either, but they were making improvements in Funimation.

**Comment by hama3254** [comment]
i can not see a problem there, you need to logged in at the downloader because of `"This video contains mature content."` but i see no other issue.
![grafik](https://user-images.githubusercontent.com/52826614/114736647-8cc62700-9d46-11eb-9b19-ad579c4e777b.png)

**Comment by NatsuFT36** [comment]
That is, although the one I downloaded from Shingeki no Kyojin are dubbing and from there they are broadcast but still later I will send you the captures if the error persists.

**Comment by Dantrech** [comment]
As of today, I am having trouble downloading from Funimation. Can't find the resolutions, it happens to me with several Anime, not only with 1. And it happens to me in both old and new Anime.

![error1](https://user-images.githubusercontent.com/791234/114752641-88891200-9d24-11eb-8f65-fb586024e00f.png)
![error2](https://user-images.githubusercontent.com/791234/114752823-b8d0b080-9d24-11eb-942b-2ba9fc1197c2.png)
[log.txt](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/files/6312615/log.txt)

**Comment by Dantrech** [comment]
Using the included browser:

![error](https://user-images.githubusercontent.com/791234/114753966-0ac60600-9d26-11eb-813b-e9f51d411de1.png)

**Comment by 619beave** [comment]
I am also getting the error on English Dub episode 8 of Log Horizon

Tim Lider

Red Belt at Cardenas School of Arnis
<https://www.facebook.com/CardenasArnis/>
Anime Enthusiast

**Comment by hama3254** [comment]
> As of today, I am having trouble downloading from Funimation. Can't find the resolutions, it happens to me with several Anime, not only with 1. And it happens to me in both old and new Anime.
> 
> ![error_3](https://user-images.githubusercontent.com/791234/114754925-17972980-9d27-11eb-9dda-bd13eef6e843.png)

i don't have access to anything premium and i don't find any Spanish dubbed anime for the free plan but i see if i can fix the resolution search with the data from the screenhot.

Japanese with subs works fine for me.
![grafik](https://user-images.githubusercontent.com/52826614/114765395-68c60e00-9d65-11eb-83d0-50f83097c5d0.png)

**Comment by Dantrech** [comment]
> Japanese with subs works fine for me.
> ![grafik](https://user-images.githubusercontent.com/52826614/114765395-68c60e00-9d65-11eb-83d0-50f83097c5d0.png)

I tried "Super Cub", episode 2 (Japanese with subs) and "screen resolution not found" appears. I configure CR Downloader with 1080p resolution.

**Comment by hama3254** [comment]
> I tried "Super Cub", episode 2 (Japanese with subs) and "screen resolution not found" appears. I configure CR Downloader with 1080p resolution.

there is just one episode for me, i assume it has something to do with my US VPN that i need to access funimation from Central Europe and not like you from Mexico. 

![grafik](https://user-images.githubusercontent.com/52826614/114767939-8ea0e200-9d68-11eb-80eb-aa2aa6db9447.png)


and that what i can test works perfectly fine.
![grafik](https://user-images.githubusercontent.com/52826614/114768187-d3c51400-9d68-11eb-8ad5-db280f4c173f.png)

**Comment by hama3254** [comment]
> As of today, I am having trouble downloading from Funimation. Can't find the resolutions, it happens to me with several Anime, not only with 1. And it happens to me in both old and new Anime.
> 
> ![error_3](https://user-images.githubusercontent.com/791234/114754925-17972980-9d27-11eb-9dda-bd13eef6e843.png)

i made some adjustments for the not found dialogue in v3.7.8.4 it now saves a `Funimation-Resolution.log` with the data it get's
https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/v3.7.8.3

**Comment by Dantrech** [comment]
> i made some adjustments for the not found dialogue in v3.7.8.4 and it now saves a `Funimation-Resolution.log` with the data it get's

New window:

![sshot-1](https://user-images.githubusercontent.com/791234/114770049-fdfedd80-9d38-11eb-870e-e6462cb77ee5.png)

If I press "X":

![sshot-2](https://user-images.githubusercontent.com/791234/114770115-10791700-9d39-11eb-92ee-797e58d5f71b.png)

Log file:  [Funimation-Resolution.log](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/files/6313353/Funimation-Resolution.log)

**Comment by lemming104** [comment]
If you look at the structure of the top-level M3U8 file, they've made some pretty major format changes.  Previously, it just contained a list of available resolutions and stream rates.  They're now using "independent segments".  Basically, what they've done is separate the audio and video streams.  There is now one audio stream that is used regardless of video resolution/bitrate (as far as I can tell), and then the video streams themselves have no audio in them.  Below is an example (with the URLs themselves scrubbed out).

As an added treat, with the two or three files I've played around with so far, the .aac audio stream has some characteristics that FFMPEG does not like.  As a result, even if you run FFMPEG in stream-copy mode, it'll cut off the audio around the five minute mark.  So, it may be necessary to use a different application to mux the streams together (or I'm just really bad with setting the correct command line parameters in FFMPEG).

Funimation only seems to have done this with streams for this new season's shows.

```
#EXTM3U
#EXT-X-VERSION:4
#EXT-X-INDEPENDENT-SEGMENTS
## Created with Unified Streaming Platform (version=1.10.28-22802)
#EXT-X-SESSION-KEY:METHOD=AES-128,URI="{some key URL}"

# AUDIO groups
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="audio-aacl-128",LANGUAGE="ja",NAME="Japanese",DEFAULT=YES,AUTOSELECT=YES,CHANNELS="2",URI="{some audio URL}"

# variants
#EXT-X-STREAM-INF:BANDWIDTH=2312000,AVERAGE-BANDWIDTH=1624000,CODECS="avc1.4D4028,mp4a.40.2",RESOLUTION=960x540,FRAME-RATE=23.976,AUDIO="audio-aacl-128",CLOSED-CAPTIONS=NONE
{some video URL}
#EXT-X-STREAM-INF:BANDWIDTH=6759000,AVERAGE-BANDWIDTH=4439000,CODECS="avc1.4D4028,mp4a.40.2",RESOLUTION=1920x1080,FRAME-RATE=23.976,AUDIO="audio-aacl-128",CLOSED-CAPTIONS=NONE
{some video URL}
#EXT-X-STREAM-INF:BANDWIDTH=5112000,AVERAGE-BANDWIDTH=3482000,CODECS="avc1.4D4028,mp4a.40.2",RESOLUTION=1280x720,FRAME-RATE=23.976,AUDIO="audio-aacl-128",CLOSED-CAPTIONS=NONE
{some video URL}
#EXT-X-STREAM-INF:BANDWIDTH=8802000,AVERAGE-BANDWIDTH=5946000,CODECS="avc1.4D4028,mp4a.40.2",RESOLUTION=1920x1080,FRAME-RATE=23.976,AUDIO="audio-aacl-128",CLOSED-CAPTIONS=NONE
{some video URL}
#EXT-X-STREAM-INF:BANDWIDTH=340000,AVERAGE-BANDWIDTH=289000,CODECS="avc1.4D4028,mp4a.40.2",RESOLUTION=416x234,FRAME-RATE=23.976,AUDIO="audio-aacl-128",CLOSED-CAPTIONS=NONE
{some video URL}
#EXT-X-STREAM-INF:BANDWIDTH=557000,AVERAGE-BANDWIDTH=445000,CODECS="avc1.4D4028,mp4a.40.2",RESOLUTION=640x360,FRAME-RATE=23.976,AUDIO="audio-aacl-128",CLOSED-CAPTIONS=NONE
{some video URL}
#EXT-X-STREAM-INF:BANDWIDTH=941000,AVERAGE-BANDWIDTH=714000,CODECS="avc1.4D4028,mp4a.40.2",RESOLUTION=768x432,FRAME-RATE=23.976,AUDIO="audio-aacl-128",CLOSED-CAPTIONS=NONE
{some video URL}
#EXT-X-STREAM-INF:BANDWIDTH=3430000,AVERAGE-BANDWIDTH=2271000,CODECS="avc1.4D4028,mp4a.40.2",RESOLUTION=1280x720,FRAME-RATE=23.976,AUDIO="audio-aacl-128",CLOSED-CAPTIONS=NONE
{some video URL}
#EXT-X-STREAM-INF:BANDWIDTH=1350000,AVERAGE-BANDWIDTH=1005000,CODECS="avc1.4D4028,mp4a.40.2",RESOLUTION=768x432,FRAME-RATE=23.976,AUDIO="audio-aacl-128",CLOSED-CAPTIONS=NONE
{some video URL}

# keyframes
#EXT-X-I-FRAME-STREAM-INF:BANDWIDTH=1002000,AVERAGE-BANDWIDTH=531000,CODECS="avc1.4D4028",RESOLUTION=960x540,URI="{some thumbnail URL}"
#EXT-X-I-FRAME-STREAM-INF:BANDWIDTH=2854000,AVERAGE-BANDWIDTH=1398000,CODECS="avc1.4D4028",RESOLUTION=1920x1080,URI="{some thumbnail URL}"
#EXT-X-I-FRAME-STREAM-INF:BANDWIDTH=2054000,AVERAGE-BANDWIDTH=1053000,CODECS="avc1.4D4028",RESOLUTION=1280x720,URI="{some thumbnail URL}"
#EXT-X-I-FRAME-STREAM-INF:BANDWIDTH=3525000,AVERAGE-BANDWIDTH=1709000,CODECS="avc1.4D4028",RESOLUTION=1920x1080,URI="{some thumbnail URL}"
#EXT-X-I-FRAME-STREAM-INF:BANDWIDTH=75000,AVERAGE-BANDWIDTH=49000,CODECS="avc1.4D4028",RESOLUTION=416x234,URI="{some thumbnail URL}"
#EXT-X-I-FRAME-STREAM-INF:BANDWIDTH=186000,AVERAGE-BANDWIDTH=112000,CODECS="avc1.4D4028",RESOLUTION=640x360,URI="{some thumbnail URL}"
#EXT-X-I-FRAME-STREAM-INF:BANDWIDTH=369000,AVERAGE-BANDWIDTH=214000,CODECS="avc1.4D4028",RESOLUTION=768x432,URI="{some thumbnail URL}"
#EXT-X-I-FRAME-STREAM-INF:BANDWIDTH=1506000,AVERAGE-BANDWIDTH=777000,CODECS="avc1.4D4028",RESOLUTION=1280x720,URI="{some thumbnail URL}"
#EXT-X-I-FRAME-STREAM-INF:BANDWIDTH=556000,AVERAGE-BANDWIDTH=308000,CODECS="avc1.4D4028",RESOLUTION=768x432,URI="{some thumbnail URL}"
```

**Comment by hama3254** [comment]
It is good to know where the issues are coming from, Thanks @lemming104 and @Dantrech but unfortunately  i can't find a Series/Episode that is free and has the new version on it 
![grafik](https://user-images.githubusercontent.com/52826614/114896915-088ca600-9e11-11eb-83a1-171eef57192f.png)

**Comment by Dantrech** [comment]
> It is good to know where the issues are coming from, Thanks @lemming104 and @Dantrech but unfortunately i can't find a Series/Episode that is free and has the new version on it

Do you need a premium account? I could pay you a month if you need it.

**Comment by NatsuFT36** [comment]
I was trying to download with premium and the same thing happens without anything and according to what the problem was found was that which happened since Tuesday through the unique series of Funimation that all the modification began

**Comment by hama3254** [comment]
> 
> 
> > It is good to know where the issues are coming from, Thanks @lemming104 and @Dantrech but unfortunately i can't find a Series/Episode that is free and has the new version on it
> 
> Do you need a premium account? I could pay you a month if you need it.

it seems like i need one, but i don't like that someone pays a new account just for me.
if you already have one it would be a help if you could give me access for a view days, the other option would be to wait and see if or when they convert the older/free videos.

**Comment by Dantrech** [comment]
> it seems like i need one, but i don't like that someone pays a new account just for me.
> if you already have one it would be a help if you could give me access for a view days, the other option would be to wait and see if or when they convert the older/free videos.

Write me your email to send you the account information, it is active until April 29.

**Comment by hama3254** [comment]
> Write me your email to send you the account information, it is active until April 29.

Thank you! 
my e-mail is hama32546@web.de

**Comment by Dantrech** [comment]
> Thank you!
> my e-mail is [hama32546@web.de](mailto:hama32546@web.de)

Done, check your mail.

**Comment by dnr18lol** [comment]
@hama3254, if you need access to a Funimation premium account, I can share my account info with you indefinetly. No problems. You are helping us a lot with this tool and receive nothing in return. I won't bother to pay you a premium account.

**Comment by hama3254** [comment]
@dnr18lol i already got one for now but thanks for the offer.

with the account i also make progress : 
i continue tomorrow because it gets late.
![grafik](https://user-images.githubusercontent.com/52826614/114932502-de021380-9e37-11eb-8047-a924b826b820.png)

**Comment by lemming104** [comment]
Don't be surprised if you find that FFMPEG thinks there's invalid data in
the audio stream.  I don't know what Funimation has done to those, but with
the two I've played around with so far, both had what FFMPEG thought was a
corrupted audio frame about five minutes in, so the audio cuts out after
that, even in "stream copy" mode, which is just *fantastic.*

**Comment by hama3254** [comment]
@lemming104 did you use any kind of bitstream filter like [aac_adtstoasc](http://www.ffmpeg.org/ffmpeg-bitstream-filters.html#aac_005fadtstoasc)?

**Comment by dnr18lol** [comment]
I've been doing some testing and I've found also something estrange regarding subs in Funimation. I don't know if is related so I'll post it here instead of opening a new issue.

When trying to download _Darling In The Franxx_, some subs are not downloaded and a error log is displayed instead. I downloaded episodes 1-6 and the error happened in episodes 3-5. 

A screencapture and the logs can be found in this drive folder: http://tiny.cc/tw4wtz

**Comment by dnr18lol** [comment]
PS: 
I've also found that when trying to download _Spice and Wolf _ even though the show it's in 1080p the downloader just find up to 480p. I've check with YT-DL and YT-DL indeed finds a 1080p quality version.
Screencapture: https://is.gd/dtzjQ0

**Comment by hama3254** [comment]
> PS:
> I've also found that when trying to download _Spice and Wolf _ even though the show it's in 1080p the downloader just find up to 480p. I've check with YT-DL and YT-DL indeed finds a 1080p quality version.
> Screencapture: https://is.gd/dtzjQ0

the downloader is only gets the resolution up to 480p so i need to find the issue why there are different datasets issued by funimation.
![grafik](https://user-images.githubusercontent.com/52826614/115037489-cfb30680-9ece-11eb-9bb5-a918fb469621.png)

**Comment by lemming104** [comment]
> 
> 
> @lemming104 did you use any kind of bitstream filter like [aac_adtstoasc](http://www.ffmpeg.org/ffmpeg-bitstream-filters.html#aac_005fadtstoasc)?

No, I just let it auto-detect.  However, even if I _do_ specify the bitstream filter, it still fails after ~5 minutes of audio.  For example, here's what I get if I run FFMPEG on the audio from "Super Cub" episode 2 (which I've already decrypted, and it plays correctly in VLCPlayer and various other applications):

```
.\ffmpeg.exe -i 'D:\Media\Super Cub Episode 2\audio_decrypted.aac' -bsf:a aac_adtstoasc -c copy 'D:\media\Super Cub Episode 2\audio_decap.aac'
ffmpeg version N-100635-gbf1cc9a43b Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 10.2.0 (Rev5, Built by MSYS2 project)
  configuration:
  libavutil      56. 63.101 / 56. 63.101
  libavcodec     58.117.101 / 58.117.101
  libavformat    58. 65.101 / 58. 65.101
  libavdevice    58. 11.103 / 58. 11.103
  libavfilter     7. 95.100 /  7. 95.100
  libswscale      5.  8.100 /  5.  8.100
  libswresample   3.  8.100 /  3.  8.100
[aac @ 00000267b2487d80] Format aac detected only with low score of 1, misdetection possible!
[aac @ 00000267b2487d80] Estimating duration from bitrate, this may be inaccurate
Input #0, aac, from 'D:\Media\Super Cub Episode 2\audio_decrypted.aac':
  Duration: 00:23:51.56, bitrate: 134 kb/s
    Stream #0:0: Audio: aac (LC), 48000 Hz, stereo, fltp, 134 kb/s
File 'D:\media\Super Cub Episode 2\audio_decap.aac' already exists. Overwrite? [y/N] Y
Output #0, adts, to 'D:\media\Super Cub Episode 2\audio_decap.aac':
  Metadata:
    encoder         : Lavf58.65.101
    Stream #0:0: Audio: aac (LC), 48000 Hz, stereo, fltp, 134 kb/s
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
Press [q] to stop, [?] for help
D:\Media\Super Cub Episode 2\audio_decrypted.aac: Invalid data found when processing input
size=    4880kB time=00:05:05.98 bitrate= 130.6kbits/s speed=1.16e+04x
video:0kB audio:4782kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 2.050685%
```
The resulting audio file is ~5 minutes long, so FFMPEG clearly just bails out rather than continuing after the malformed data.

If I get some time to do so, I may write some code to walk through the ADTS stream and copy only "well formed" frames.

**Comment by dnr18lol** [comment]
> > PS:
> > I've also found that when trying to download _Spice and Wolf _ even though the show it's in 1080p the downloader just find up to 480p. I've check with YT-DL and YT-DL indeed finds a 1080p quality version.
> > Screencapture: https://is.gd/dtzjQ0
> 
> Edit: i checked that and it seems not an issue with the downloader, Japanese Dub is just up to 480p while english dub gets up to 1080p
> ![grafik](https://user-images.githubusercontent.com/52826614/115039966-3afdd800-9ed1-11eb-81ce-bce8817f2989.png)
> 
> original text

Yep. That seems to be the problem. My bad there. Thanks.

**Comment by hama3254** [comment]
@lemming104 i tried one audio file without any issue by just directly downloading and decrypting it with ffmpeg

```
C:\Windows\System32>ffmpeg.exe -user-agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:87.0) Gecko/20100101 Firefox/87.0" -i "[url]" -c copy -bsf:a aac_adtstoasc "E:\Test\Test.aac"
ffmpeg version 4.2.3 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 9.3.1 (GCC) 20200523
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
[https @ 067d54c0] The "user-agent" option is deprecated: use the "user_agent" option instead
[hls @ 067d4700] Skip ('#EXT-X-VERSION:4')
[hls @ 067d4700] Skip ('## Created with Unified Streaming Platform (version=1.10.28-22802)')
[hls @ 067d4700] Skip ('#USP-X-MEDIA:BANDWIDTH=134000,AVERAGE-BANDWIDTH=131000,TYPE=AUDIO,GROUP-ID="audio-aacl-128",LANGUAGE="ja",NAME="Japanese",AUTOSELECT=YES,CHANNELS="2",CODECS="mp4a.40.2"')
[hls @ 067d4700] Opening '[url].key' for reading
[hls @ 067d4700] Opening 'crypto+[url]' for reading
Input #0, hls, from '[url]':
  Duration: 00:23:50.04, start: 9.957333, bitrate: 3 kb/s
  Program 0
    Metadata:
      variant_bitrate : 0
    Stream #0:0: Audio: aac (LC), 48000 Hz, stereo, fltp, 132 kb/s
    Metadata:
      variant_bitrate : 0
      id3v2_priv.com.apple.streaming.transportStreamTimestamp: \x00\x00\x00\x00\x00\x0d\xac\xa0
Output #0, adts, to 'E:\Test\Test.aac':
  Metadata:
    encoder         : Lavf58.29.100
    Stream #0:0: Audio: aac (LC), 48000 Hz, stereo, fltp, 132 kb/s
    Metadata:
      variant_bitrate : 0
      id3v2_priv.com.apple.streaming.transportStreamTimestamp: \x00\x00\x00\x00\x00\x0d\xac\xa0
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
Press [q] to stop, [?] for help
[hls @ 067d4700] Opening 'crypto+[url]' for reading
[hls @ 067d4700] Opening 'crypto+[url]' for reading
[hls @ 067d4700] Opening 'crypto+[url]' for reading
[hls @ 067d4700] Opening 'crypto+[url]' for reading
size=   22803kB time=00:23:50.03 bitrate= 130.6kbits/s speed=2.58x
video:0kB audio:22345kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 2.050781%
```

**Comment by lemming104** [comment]
Could be an issue with my build of FFMPEG, I suppose, or could just be an
issue with some of their files and not others. Something to keep an eye out
for, in any case.

**Comment by hama3254** [comment]
> I've been doing some testing and I've found also something strange regarding subs in Funimation. I don't know if it's related so I'll post it here instead of opening a new issue.
> 
> When trying to download _Darling In The Franxx_, some subs are not downloaded and an error log is displayed instead. I downloaded episodes 1-6 and the error happened in episodes 3-5.
 
it seems like for that Anime are two version available, `Uncut` and `Simulcast` version and just one of them has subs.
Which one you get after opening the video on funimation is as random as it seems, for you episode 6 worked with subs for me not as example. 

![grafik](https://user-images.githubusercontent.com/52826614/115054490-8c619380-9ee0-11eb-9005-867ad132f1b5.png)

**Comment by Dantrech** [comment]
> it seems like for that Anime are two version available, `Uncut` and `Simulcast` version and just one of them has subs.

Mmm, I think "simulcast" is played wheb the url have "/simulcast/", and uncut when no. Check my previus images and look the URL's.

**Comment by hama3254** [comment]
> Mmm, I think "simulcast" is played when the url have "/simulcast/", and uncut when no. Check my previus images and look the URL's.

they have both option for the URL but it does not work, it just ignores it ...
https://youtu.be/mrmjQJ6wFoI

so i don't see a way i can fix that part because it's on funimation to do that but.

i also released the new version which should work for both the new and old stream files.

https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/v3.7.8.5

For more about that i also made a discussion with the release, please use that for any kind of feedback.

**Comment by NatsuFT36** [comment]
Now the error appears on Crunchyroll in premium downloads such as the chapter So I'm a Spider, So What? It only downloads the sub while the video is downloading, but it stops asking to restart the download again.

On the other hand, the one from Funimation already downloads the subs but without selecting hybrid mode, since if I enable it, nothing is downloaded and more than from the Task Manager it runs a downloadable network. On the other hand they still do not download the videos yet and I tried it on today's broadcast from that link:
https://www.funimation.com/shows/blue-reflection-ray/without-a-single-friend/?qid=

**Comment by Dantrech** [comment]
Error persist in last version.

![sshot-1](https://user-images.githubusercontent.com/791234/115087157-ae0c4c00-9edb-11eb-910b-3e6cfb3dc654.png)

**Comment by hama3254** [comment]
> 
> 
> Error persist in last version.
> 
> ![sshot-1](https://user-images.githubusercontent.com/791234/115087157-ae0c4c00-9edb-11eb-910b-3e6cfb3dc654.png)

please add the log file, you can either save it or copy it to the clipboard via a right klick on the failed download

**Comment by Dantrech** [comment]
> please add the log file, you can either save it or copy it to the clipboard via a right klick on the failed download

If I deactivate subtitles (soft, hard) this is the log file:  [Attack On Titan Season 5 Episode 73.log](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/files/6328082/Attack.On.Titan.Season.5.Episode.73.log)

If I activate soft subtitles (Spanish LA) this is the log file:  [Attack On Titan Season 5 Episode 73-subtitle_error.log](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/files/6328086/Attack.On.Titan.Season.5.Episode.73-subtitle_error.log)

**Comment by NatsuFT36** [comment]
In the end if the video and sub worked but without the option of "hybrid download" although it is slow but waiting for you to add that option to force fast downloads from Funimation since the previous chapters keep that format with 256 kbps audio but the new series will be carried with 128 kbps of audio.

**Comment by hama3254** [comment]
> > please add the log file, you can either save it or copy it to the clipboard via a right klick on the failed download
> 
> If I deactivate subtitles (soft, hard) this is the log file: [Attack On Titan Season 5 Episode 73.log](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/files/6328082/Attack.On.Titan.Season.5.Episode.73.log)
> 
> If I activate soft subtitles (Spanish LA) this is the log file: [Attack On Titan Season 5 Episode 73-subtitle_error.log](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/files/6328086/Attack.On.Titan.Season.5.Episode.73-subtitle_error.log)
> 
> PD: The epidose is Spanish LA dubbed.

It seems like i did not adjust the download command for every case correctly. I fix that soon.

**Comment by hama3254** [comment]
> In the end if the video and sub worked but without the option of "hybrid download" although it is slow but waiting for you to add that option to force fast downloads from Funimation since the previous chapters keep that format with 256 kbps audio but the new series will be carried with 128 kbps of audio.

I work on the hybrid mode as soon i have the time for it, my priority is that the normal download is working as intended.

**Comment by hama3254** [comment]
i uploaded a new version that should fix the download commands for every case with merged subs.
https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/v3.7.8.6

**Comment by psjmaster** [comment]
Fantastic, now it is working correctly without errors. Congratulations for the excellent work.
Thank you very much!

**Comment by psjmaster** [comment]
> Eu carreguei uma nova versão que deve corrigir os comandos de download para cada caso com subs mesclados.
> https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/v3.7.8.6

Fantastic, now it is working correctly without errors. Congratulations for the excellent work. Thank you very much!

**Comment by Dantrech** [comment]
> If I deactivate subtitles (soft, hard) this is the log file: (removed for security reasons)
> > It seems like i did not adjust the download command for every case correctly. I fix that soon.

Ok, fixed in the last version!

> If I activate soft subtitles (Spanish LA) this is the log file: (removed for security reasons)
PD: The epidose is Spanish LA dubbed.
> > There is nothing wrong with the subtitle search from the downloader, that video just does not has any.
Please keep in mind that i can't detect if there are multiple streams for a video url i just use what's in player on the page you open and that might be a version with out subs.

Yes and no. In previous versions, even if the subtitle was not found the episode was still downloaded, but when I sent you the log, the application said that it could not find the subtitle and did nothing (the episode was not downloading ). The good thing is that with the latest version you uploaded, it works fine again!, even if it can't find the subtitle, the episode is downloaded.

So, yeah, for now everything looks good! Thanks!!!

PD: I will look forward to the hybrid mode fix.
