### ISSUE TITLE
no media found error 

### ISSUE THREAD

**Issue by surgeonofdeath** [hama3254/Crunchyroll-Downloader-v3.0#367]
![2021-10-11 (2)](https://user-images.githubusercontent.com/92287668/136734574-257365cc-b3f0-44a6-8e67-f5f6ff1faac7.png)

when i go to download a video, its been giving me problems-- showing this error message. currently on v.3.7.8.6. & v.3.8. Beta - U13. i was recently on U10 & it was giving me the same problem.

**Comment by surgeonofdeath** [comment]
OK, still new to this lmao. so plz bare with me & i’ll test it out in the morning & come back if problems persist

**Comment by hama3254** [comment]
`Crunchyroll-Downloader-Chromium-U4` is not the latest version and funimation is currently try and error since they have fun changing stuff so i just uploaded [Crunchyroll-Downloader-Chromium-Hotfix-357_5](https://github.com/hama3254/Crunchyroll-Downloader-v3.0/releases/tag/v3.x) which you can try.

**Comment by surgeonofdeath** [comment]
it works, thanks !

**Comment by surgeonofdeath** [comment]
it works, thanks !

**Comment by hama3254** [comment]
> still giving me problems after trying that version. i was able to get one video & that's it.

If you could tell me the issue(s) you have now i could a look at it later but guessing a issue for hundreds of lines of code is impossible.

**Comment by hama3254** [comment]
You send me two error Messages, the first means you need a premium account and be logged in inside the build-in Webbrowser.
The second should be fixed but if not there is a clear information where the issue is located at the end of that message.

**Comment by surgeonofdeath** [comment]
![2021-10-13](https://user-images.githubusercontent.com/92287668/137236574-389c959b-d2b1-45dd-8ba6-13893e29e8a4.png)

i am logged in to my premium account as well. problem still taking place.
